const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const buildPath = (name) => path.join(__dirname, '..', 'build', name)
const installer = fs.readFileSync(buildPath('installer.nsh'), 'utf8')
const ensureTap = fs.readFileSync(buildPath('ensure-wel-tap.ps1'), 'utf8')
const removeTap = fs.readFileSync(buildPath('remove-wel-tap.ps1'), 'utf8')
const hideTapWindows = fs.readFileSync(buildPath('hide-tap-windows.ps1'), 'utf8')
const cleanupOpenVpnGui = fs.readFileSync(buildPath('cleanup-openvpn-gui.ps1'), 'utf8')

test('bundles the OpenVPN runtime and installs the Win7-compatible TAP helper', () => {
  assert.match(installer, /tap-windows-9\.21\.2\.exe/)
  assert.match(installer, /wel-tap-win7\.exe" \/S/)
  assert.match(installer, /remember-installed-tap\.ps1/)
  assert.match(installer, /tap-before\.txt/)
  assert.doesNotMatch(installer, /OpenVPN-2\.5\.10-I601-amd64\.msi/)
  assert.doesNotMatch(installer, /TAPWINDOWS6ADAPTERS=0/)
  assert.doesNotMatch(installer, /ARPSYSTEMCOMPONENT=1/)
  assert.doesNotMatch(installer, /tap-windows-9\.24\.7-I601-Win7\.exe/)
  assert.match(installer, /cleanup_previous_msi_done/)
  assert.match(installer, /remove-wel-openvpn-msi\.ps1/)
  assert.doesNotMatch(installer, /Drivers\.Wintun|ADDLOCAL=[^\r\n]*OpenVPN,Drivers/)
  assert.match(installer, /resources\\openvpn\\bin\\openvpn\.exe/)
  assert.match(installer, /File \/oname=wel-tapctl\.exe/)
  assert.match(installer, /ensure-wel-tap\.ps1/)
  assert.match(installer, /remove-wel-tap\.ps1/)
  assert.match(installer, /remove-wel-openvpn-msi\.ps1/)
  assert.match(installer, /hide-tap-windows\.ps1/)
})

test('reuses one WEL adapter across upgrades and removes old WEL duplicates', () => {
  assert.doesNotMatch(ensureTap, /NetConnectionID -eq 'WEL TAP'/)
  assert.match(ensureTap, /Remove-NumberedWelTapAdapters/)
  assert.match(ensureTap, /WEL TAP|WEL Virtual LAN/)
  assert.match(ensureTap, /Get-WmiObject -Class Win32_NetworkAdapter/)
  assert.doesNotMatch(ensureTap, /Get-NetAdapter/)
  assert.match(removeTap, /for \(\$i = 2; \$i -le 50; \$i\+\+\)/)
  assert.match(removeTap, /WEL Virtual LAN/)
  assert.match(removeTap, /tap-create\.txt/)
  assert.match(removeTap, /delete \$rememberedGuid/)
  assert.match(removeTap, /& \$TapctlPath delete \$name/)
})

test('keeps the Windows network connection name stable on Windows 7', () => {
  assert.doesNotMatch(ensureTap, /Set-TapConnectionName/)
  assert.doesNotMatch(ensureTap, /Set-ItemProperty -LiteralPath \$connectionKey -Name 'Name'/)
  assert.doesNotMatch(removeTap, /Release-WelTapConnectionNames/)
  assert.match(ensureTap, /Windows-assigned connection name/)
})

test('hides TAP/OpenVPN entries without hiding WEL', () => {
  assert.match(hideTapWindows, /SystemComponent/)
  assert.match(hideTapWindows, /TAP\[- \]Windows/)
  assert.match(installer, /hide-tap-windows\.ps1/)
  assert.doesNotMatch(installer, /\$COMMONAPPDATA/)
})

test('runs installer system commands without visible console windows', () => {
  assert.doesNotMatch(installer, /ExecWait/)
  assert.match(installer, /nsExec::ExecToLog[^\n]+powershell\.exe/)
})

test('removes unused OpenVPN GUI shortcuts and startup entries', () => {
  assert.match(installer, /cleanup-openvpn-gui\.ps1/)
  assert.match(installer, /\$SMSTARTUP\\OpenVPN GUI\.lnk/)
  assert.match(installer, /DeleteRegValue HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Run" "OpenVPN GUI"/)
  assert.match(installer, /DeleteRegValue HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Run" "OpenVPN GUI"/)
  assert.match(installer, /DeleteRegValue HKLM "Software\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Run" "OpenVPN GUI"/)
  assert.match(installer, /taskkill\.exe" \/F \/IM openvpn-gui\.exe/)
  assert.match(cleanupOpenVpnGui, /CommonStartup/)
  assert.match(cleanupOpenVpnGui, /Remove-ItemProperty/)
  assert.match(cleanupOpenVpnGui, /Get-ScheduledTask/)
  assert.match(cleanupOpenVpnGui, /Unregister-ScheduledTask/)
  assert.match(installer, /Sysnative\\WindowsPowerShell/)
  assert.match(installer, /SetRegView 64/)
  assert.match(installer, /SetRegView 32/)
})
